name: 'Deploy react app to github pages'

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run |
        npm ci
        npm run build
        git config user.name github-actions
        git config user.email github-actions@github.com
        git --work-tree build add --all
        git commit -m "Automatic Deploy action run by github-actions"
        git push origin HEAD:gh-pages --force
